### ISSUE TITLE
Sensors.js should be lowercase

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [fabiorogeriosj/cordova-plugin-sensors#4]
When installing on a linux machine I get this error:
```
Installing "com.fabiorogeriosj.sensors" for android
Error during processing of action! Attempting to revert...
Failed to install 'com.fabiorogeriosj.sensors':CordovaError: Uh oh!
"/home/ben/basis-alignment/app/plugins/com.fabiorogeriosj.sensors/www/sensors.js" not found!
    at copyFile (/home/ben/basis-alignment/app/platforms/android/cordova/lib/pluginHandlers.js:202:36)
    at handlers.asset.install (/home/ben/basis-alignment/app/platforms/android/cordova/lib/pluginHandlers.js:129:13)
    at Object.ActionStack.process (/home/ben/basis-alignment/app/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/ben/basis-alignment/app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/home/ben/basis-alignment/app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at Api.addPlugin (/home/ben/basis-alignment/app/platforms/android/cordova/Api.js:198:10)
    at handleInstall (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:611:6)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:407:28
    at _fulfilled (/usr/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/q/q.js:816:30)
Error: Uh oh!
"/home/ben/basis-alignment/app/plugins/com.fabiorogeriosj.sensors/www/sensors.js" not found!
```
It can be fixed by using a lowercase filename: Sensors.js -> sensors.js

**Comment by Spiritdude** [comment]
+1
